In [1]:
x = [
    [1,2,3],
    [2,3,4],
    [3,4,5]
]
print(x)

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]


In [2]:
#[[6,7,8],[7,8,9],[8,9,10]]
# if u need this u have to use loop
x5 =[]
for i in x:
    temp = []
    for j in i:
        temp.append(j+5)
    x5.append(temp)
x5

[[6, 7, 8], [7, 8, 9], [8, 9, 10]]

In [4]:
#the power of numpy
import numpy as np

In [6]:
x = np.array(x)
print(x)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [7]:
print(x+5)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [8]:
print(x-5)

[[-4 -3 -2]
 [-3 -2 -1]
 [-2 -1  0]]


In [9]:
print(x*5)

[[ 5 10 15]
 [10 15 20]
 [15 20 25]]


In [10]:
print(x/5)

[[0.2 0.4 0.6]
 [0.4 0.6 0.8]
 [0.6 0.8 1. ]]


In [11]:
print(x//5)

[[0 0 0]
 [0 0 0]
 [0 0 1]]


# basics to numpy
i).creating numpy arrays
ii).using functions to manipulate arrays 

In [12]:
x = [1,2,3,4]

In [13]:
nx = np.array(x)

In [16]:
type(nx)

numpy.ndarray

In [17]:
y = (1,2,3,4,5)
y = np.array(y)

In [18]:
x = np.array(x)

In [19]:
x

array([1, 2, 3, 4])

In [20]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros((4,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
np.ones((4,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.diag([4,5,3,7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [47]:
z = np.arange(1,100,50)

In [48]:
print(z)

[ 1 51]


In [49]:
np.linspace(1,100,13)

array([  1.  ,   9.25,  17.5 ,  25.75,  34.  ,  42.25,  50.5 ,  58.75,
        67.  ,  75.25,  83.5 ,  91.75, 100.  ])

In [50]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])